[package]
authors = ["Erick Machado <erick.gsmachado@gmail.com>"]
edition = "2021"
name = "zero2prod"
version = "0.0.1"

[dependencies]
actix-web = "4"
tokio = { features = ["macros", "rt-multi-thread"], version = "1" }
